import React, { Component } from 'react';
import {
  Deck, Slide, Text, Heading, Image, Link, S
} from 'spectacle';

// Import theme
import createTheme from 'spectacle/lib/themes/default';

// Import images
import intro from './assets/intro.gif';
import githubProfile from './assets/githubProfile.png';
import ternopil from './assets/ternopil.jpg';

// Colors generated by Coolors:
// https://coolors.co/2b2d42-f4faff-dee7e7-ef233c-19647e
const colors = {
  primary: "#F5FBEF",
  secondary: "#19647E",
  tertiary: "#EF233C",
  quartenary: "#2B2D42",
  // colors
  gunmental: "#2B2D42",
  alice: "#F4FAFF",
  platinum: "#DEE7E7",
  red: "#EF233C",
  blue: "#19647E"
};

const fonts = {
  primary: {
    name: 'Fira Sans',
    googleFont: true,
    styles: ['300', '700']
  },
  secondary: 'Helvetica'
};

const theme = createTheme(colors, fonts)

export default class App extends Component {
  render() {
    return (
      <Deck transition={['fade']} transitionDuration={500} theme={theme} progress="bar">
        <Slide bgImage={ternopil} bgDarken={0.5}>
          <Heading textColor="alice">Hello, Ternopil!</Heading>
        </Slide>

        <Slide bgColor="white">
          <Image src={githubProfile} width="100%" margin="-4rem auto 0"/>
        </Slide>

        <Slide bgImage={intro} bgDarken={0.5}>
          <Heading fit caps textColor="alice">A crash-course into</Heading>
          <Heading fit caps>virtual</Heading>
          <Heading fit caps>reality</Heading>
          <Heading fit caps textColor="alice">for web-developers</Heading>
        </Slide>

        <Slide>
          <Text>slides…</Text>
        </Slide>

        <Slide>
          <Link href="https://twitter.com/denysdovhan">
            <Heading>
              <S type="underline">@denysdovhan</S>
            </Heading>
          </Link>
        </Slide>

        <Slide>
          <Heading textColor="blue">
            Дякую за увагу!
          </Heading>
          <Text margin="1rem auto" lineHeight={1.2}>2 Sep 2017</Text>
          <Link href="#">
            <Text margin="6em auto" textSize="2rem">
              Slides: denysdovhan.com/slides-vr-crash-course
            </Text>
          </Link>
        </Slide>
      </Deck>
    );
  }
}
